import pathlib

import abjad
import baca
import evans

import polillas

maker = evans.SegmentMaker(
    instruments=polillas.instruments,
    names=[
        '"Violin I"',
        '"Violin II"',
        '"Viola"',
        '"Violoncello"',
    ],
    abbreviations=[
        '"vn. I"',
        '"vn. II"',
        '"va."',
        '"vc."',
    ],
    name_staves=True,
    fermata_measures=polillas.fermata_measures_16,
    commands=[
        evans.MusicCommand(
            [
                ("violin 1 voice", (0, 2)),
                ("violin 2 voice", (0, 2)),
                ("viola voice", (0, 2)),
                ("cello voice", (0, 2)),
            ],
            polillas.flight(stage=6),
            evans.PitchHandler(
                [
                    "cs''",
                    "cs''",
                    "b'",
                    "b'",
                    "af'",
                    "af'",
                    "g'",
                    "g'",
                    "b'",
                    "b'",
                    "c''",
                    "c''",
                    "g'",
                    "g'",
                    "cs''",
                    "cs''",
                ],
                forget=False,
            ),
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(0),
            ),
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(2),
            ),
            polillas.D_color,
            preprocessor=polillas.fuse_quarters_preprocessor_2_20,
        ),
        evans.attach(
            "violin 1 voice",
            abjad.Dynamic("p"),
            polillas.select_measures([0]).leaf(0),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.StartHairpin("<|"),
            polillas.select_measures([0]).leaf(0),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.Dynamic("f"),
            polillas.select_measures([0]).leaf(1),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.Dynamic("p"),
            polillas.select_measures([0]).leaf(2),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.StartHairpin("<"),
            polillas.select_measures([0]).leaf(2),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.Dynamic("ff"),
            polillas.select_measures([1]).leaf(0),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.Dynamic("p"),
            polillas.select_measures([0]).leaf(0),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.StartHairpin("<|"),
            polillas.select_measures([0]).leaf(0),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.Dynamic("f"),
            polillas.select_measures([0]).leaf(1),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.Dynamic("p"),
            polillas.select_measures([0]).leaf(2),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.StartHairpin("<"),
            polillas.select_measures([0]).leaf(2),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.Dynamic("ff"),
            polillas.select_measures([1]).leaf(0),
        ),
        evans.attach(
            "viola voice",
            abjad.Dynamic("p"),
            polillas.select_measures([0]).leaf(0),
        ),
        evans.attach(
            "viola voice",
            abjad.StartHairpin("<|"),
            polillas.select_measures([0]).leaf(0),
        ),
        evans.attach(
            "viola voice",
            abjad.Dynamic("f"),
            polillas.select_measures([0]).leaf(1),
        ),
        evans.attach(
            "viola voice",
            abjad.Dynamic("p"),
            polillas.select_measures([0]).leaf(2),
        ),
        evans.attach(
            "viola voice",
            abjad.StartHairpin("<"),
            polillas.select_measures([0]).leaf(2),
        ),
        evans.attach(
            "viola voice",
            abjad.Dynamic("ff"),
            polillas.select_measures([1]).leaf(0),
        ),
        evans.attach(
            "cello voice",
            abjad.Dynamic("p"),
            polillas.select_measures([0]).leaf(0),
        ),
        evans.attach(
            "cello voice",
            abjad.StartHairpin("<|"),
            polillas.select_measures([0]).leaf(0),
        ),
        evans.attach(
            "cello voice",
            abjad.Dynamic("f"),
            polillas.select_measures([0]).leaf(1),
        ),
        evans.attach(
            "cello voice",
            abjad.Dynamic("p"),
            polillas.select_measures([0]).leaf(2),
        ),
        evans.attach(
            "cello voice",
            abjad.StartHairpin("<"),
            polillas.select_measures([0]).leaf(2),
        ),
        evans.attach(
            "cello voice",
            abjad.Dynamic("ff"),
            polillas.select_measures([1]).leaf(0),
        ),
        evans.MusicCommand(
            [
                ("violin 1 voice", (2, 4)),
                ("violin 2 voice", (2, 4)),
                ("viola voice", (2, 4)),
                ("cello voice", (2, 4)),
            ],
            polillas.wings(
                indices=[1, 4, 10, 15],
                period=23,
                denominator=16,
                extra_counts=[0, 2, 1, 1],
                stage=1,
            ),
            polillas.B_pitches(stage=1, transposition=-2, rotation=3),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"spazzolato =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
                selector=abjad.select().notes(),
            ),
            polillas.B_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [
                ("violin 1 voice", (4, 7)),
                ("violin 2 voice", (4, 7)),
                ("viola voice", (4, 7)),
                ("cello voice", (4, 7)),
            ],
            polillas.flight(stage=6),
            evans.PitchHandler(
                [
                    "cs''",
                    "cs''",
                    "b'",
                    "b'",
                    "af'",
                    "af'",
                    "g'",
                    "g'",
                    "b'",
                    "b'",
                    "c''",
                    "c''",
                    "g'",
                    "g'",
                    "cs''",
                    "cs''",
                ],
                forget=False,
            ),
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(0),
            ),
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(2),
            ),
            polillas.D_color,
            preprocessor=polillas.fuse_quarters_preprocessor_2_20,
        ),
        evans.attach(
            "violin 1 voice",
            abjad.Dynamic("p"),
            polillas.select_measures([4]).leaf(0),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.StartHairpin("<|"),
            polillas.select_measures([4]).leaf(0),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.Dynamic("f"),
            polillas.select_measures([4]).leaf(1),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.Dynamic("p"),
            polillas.select_measures([5]).leaf(0),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.StartHairpin("<"),
            polillas.select_measures([5]).leaf(0),
        ),
        evans.attach(
            "violin 1 voice",
            abjad.Dynamic("ff"),
            polillas.select_measures([6]).leaf(0),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.Dynamic("p"),
            polillas.select_measures([4]).leaf(0),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.StartHairpin("<|"),
            polillas.select_measures([4]).leaf(0),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.Dynamic("f"),
            polillas.select_measures([4]).leaf(1),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.Dynamic("p"),
            polillas.select_measures([5]).leaf(0),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.StartHairpin("<"),
            polillas.select_measures([5]).leaf(0),
        ),
        evans.attach(
            "violin 2 voice",
            abjad.Dynamic("ff"),
            polillas.select_measures([6]).leaf(0),
        ),
        evans.attach(
            "viola voice",
            abjad.Dynamic("p"),
            polillas.select_measures([4]).leaf(0),
        ),
        evans.attach(
            "viola voice",
            abjad.StartHairpin("<|"),
            polillas.select_measures([4]).leaf(0),
        ),
        evans.attach(
            "viola voice",
            abjad.Dynamic("f"),
            polillas.select_measures([4]).leaf(1),
        ),
        evans.attach(
            "viola voice",
            abjad.Dynamic("p"),
            polillas.select_measures([5]).leaf(0),
        ),
        evans.attach(
            "viola voice",
            abjad.StartHairpin("<"),
            polillas.select_measures([5]).leaf(0),
        ),
        evans.attach(
            "viola voice",
            abjad.Dynamic("ff"),
            polillas.select_measures([6]).leaf(0),
        ),
        evans.attach(
            "cello voice",
            abjad.Dynamic("p"),
            polillas.select_measures([4]).leaf(0),
        ),
        evans.attach(
            "cello voice",
            abjad.StartHairpin("<|"),
            polillas.select_measures([4]).leaf(0),
        ),
        evans.attach(
            "cello voice",
            abjad.Dynamic("f"),
            polillas.select_measures([4]).leaf(1),
        ),
        evans.attach(
            "cello voice",
            abjad.Dynamic("p"),
            polillas.select_measures([5]).leaf(0),
        ),
        evans.attach(
            "cello voice",
            abjad.StartHairpin("<"),
            polillas.select_measures([5]).leaf(0),
        ),
        evans.attach(
            "cello voice",
            abjad.Dynamic("ff"),
            polillas.select_measures([6]).leaf(0),
        ),
        evans.MusicCommand(
            [("violin 1 voice", (7, 9))],
            polillas.chilled(stage=5, rotation=0),
            polillas.E_pitches(stage=1, transposition=16, rotation=-5),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"1/2 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("violin 2 voice", (7, 9))],
            polillas.chilled(stage=5, rotation=1),
            polillas.E_pitches(stage=1, transposition=5, rotation=-7),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"1/2 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("viola voice", (8, 9))],
            polillas.chilled(stage=5, rotation=0),
            polillas.E_pitches(stage=1, transposition=-7, rotation=-9),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"1/2 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("cello voice", (8, 9))],
            polillas.chilled(stage=5, rotation=1),
            polillas.E_pitches(stage=1, transposition=-19, rotation=-11),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"1/2 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [
                ("violin 1 voice", (9, 13)),
                ("violin 2 voice", (9, 13)),
                ("viola voice", (9, 13)),
                ("cello voice", (9, 13)),
            ],
            polillas.flight(stage=6),
            evans.PitchHandler(
                [
                    "cs''",
                    "cs''",
                    "b'",
                    "b'",
                    "b'",
                    "b'",
                    "b'",
                    "af'",
                    "af'",
                    "g'",
                    "g'",
                    "g'",
                    "g'",
                    "g'",
                    "b'",
                    "b'",
                    "c''",
                    "c''",
                    "c''",
                    "c''",
                    "c''",
                    "g'",
                    "g'",
                    "cs''",
                    "cs''",
                    "cs''",
                    "cs''",
                    "cs''",
                ],
                forget=False,
            ),
            polillas.special_hairpin,
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(0),
            ),
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(2),
            ),
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(3),
            ),
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(4),
            ),
            evans.Attachment(
                abjad.Glissando(),
                selector=baca.selectors.leaf(5),
            ),
            polillas.D_color,
            preprocessor=polillas.fuse_quarters_preprocessor_2_20,
        ),
        evans.MusicCommand(
            [("violin 1 voice", (13, 23))],
            polillas.chilled(
                stage=2,
                input_counts=[
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                ],
            ),
            polillas.E_pitches(stage=1, transposition=7, rotation=0),
            abjad.Dynamic("p"),
            baca.text_spanner(
                r"1/2 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("violin 2 voice", (13, 23))],
            polillas.chilled(
                stage=2,
                input_counts=[1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2],
            ),
            polillas.E_pitches(stage=1, transposition=7, rotation=4),
            abjad.Dynamic("p"),
            baca.text_spanner(
                r"1/2 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("viola voice", (13, 23))],
            polillas.chilled(
                stage=2,
                input_counts=[2, 1, 1, 1, 2, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1],
            ),
            polillas.E_pitches(stage=1, transposition=7, rotation=8),
            abjad.Dynamic("p"),
            baca.text_spanner(
                r"1/2 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("cello voice", (13, 23))],
            polillas.chilled(
                stage=2,
                input_counts=[3, 1, 2, 1, 3, 1, 1, 2, 1, 1, 1, 2, 1],
            ),
            polillas.E_pitches(stage=1, transposition=7, rotation=12),
            abjad.Dynamic("p"),
            baca.text_spanner(
                r"1/2 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [
                ("violin 1 voice", (23, 28)),
                ("violin 2 voice", (23, 28)),
                ("viola voice", (23, 28)),
                ("cello voice", (23, 28)),
            ],
            polillas.make_tied_notes(),
            evans.PitchHandler(["c''", "cs''", "af'", "b'"], forget=False),
            polillas.D_color,
            # preprocessor=polillas.quarters_preprocessor,
        ),
        evans.call(
            "violin 1 voice",
            baca.hairpin("mf > p"),
            polillas.select_measures([23, 24, 25, 26, 27]),
        ),
        evans.call(
            "violin 2 voice",
            baca.hairpin("mf > p"),
            polillas.select_measures([23, 24, 25, 26, 27]),
        ),
        evans.call(
            "viola voice",
            baca.hairpin("mp < f"),
            polillas.select_measures([23, 24, 25, 26, 27]),
        ),
        evans.call(
            "cello voice",
            baca.hairpin("mp < f"),
            polillas.select_measures([23, 24, 25, 26, 27]),
        ),
        evans.MusicCommand(
            [
                ("violin 1 voice", (29, 32)),
                ("violin 2 voice", (29, 32)),
                ("viola voice", (28, 30)),
                ("cello voice", (28, 30)),
            ],
            polillas.make_tied_notes(),
            evans.PitchHandler(["c''", "cs''", "af'", "b'"], forget=False),
            polillas.D_color,
            # preprocessor=polillas.quarters_preprocessor,
        ),
        evans.call(
            "violin 1 voice",
            baca.hairpin("mf < f"),
            polillas.select_measures([29, 31]),
        ),
        evans.call(
            "violin 2 voice",
            baca.hairpin("mf < f"),
            polillas.select_measures([29, 31]),
        ),
        evans.call(
            "viola voice",
            baca.hairpin("mf > mp"),
            polillas.select_measures([28, 29]),
        ),
        evans.call(
            "cello voice",
            baca.hairpin("mf > mp"),
            polillas.select_measures([28, 29]),
        ),
        evans.MusicCommand(
            [("violin 1 voice", (32, 36))],
            polillas.chilled(stage=5, rotation=0),
            polillas.E_pitches(stage=1, transposition=9, rotation=1),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"3/4 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("violin 2 voice", (32, 36))],
            polillas.chilled(stage=5, rotation=1),
            polillas.E_pitches(stage=1, transposition=10, rotation=2),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"3/4 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("viola voice", (33, 36))],
            polillas.chilled(stage=5, rotation=0),
            polillas.E_pitches(stage=1, transposition=11, rotation=3),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"3/4 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.MusicCommand(
            [("cello voice", (33, 36))],
            polillas.chilled(stage=5, rotation=1),
            polillas.E_pitches(stage=1, transposition=12, rotation=4),
            abjad.Dynamic("mp"),
            baca.text_spanner(
                r"3/4 scratch =|",
                (abjad.tweak(5).staff_padding, 0),
                lilypond_id=1,
                bookend=False,
            ),
            polillas.E_color,
            preprocessor=polillas.quarters_preprocessor,
        ),
        evans.call(
            "score",
            evans.SegmentMaker.beam_score_without_splitting,
            abjad.select().components(abjad.Score),
        ),
        evans.attach(
            "Global Context",
            abjad.Markup(
                r'\markup \with-dimensions-from \null \musicglyph #"scripts.ufermata"',
                literal=True,
                direction=abjad.Up,
            ),
            abjad.select().leaves().group_by_measure().get([36]).leaf(1),
        ),
        evans.attach(
            "Global Context",
            polillas.mark_90,
            baca.selectors.leaf(0),
        ),
        evans.attach(
            "Global Context",
            polillas.met_90,
            baca.selectors.leaf(0),
        ),
        evans.attach(
            "Global Context",
            polillas.mark_120,
            baca.selectors.leaf(28),
        ),
        evans.attach(
            "Global Context",
            polillas.met_120,
            baca.selectors.leaf(28),
        ),
        # evans.call(
        #     "Global Context",
        #     evans.annotate_leaves,
        #     abjad.select(),
        # ),
        # evans.call(
        #     "violin 1 voice",
        #     evans.annotate_leaves,
        #     abjad.select(),
        # ),
        # evans.call(
        #     "violin 2 voice",
        #     evans.annotate_leaves,
        #     abjad.select(),
        # ),
        # evans.call(
        #     "viola voice",
        #     evans.annotate_leaves,
        #     abjad.select(),
        # ),
        # evans.call(
        #     "cello voice",
        #     evans.annotate_leaves,
        #     abjad.select(),
        # ),
    ],
    score_template=polillas.score,
    transpose_from_sounding_pitch=True,
    time_signatures=polillas.signatures_16,
    clef_handlers=None,
    tuplet_bracket_noteheads=False,
    add_final_grand_pause=False,
    score_includes=[
        f"{pathlib.Path(abjad.__file__).parent.parent}/docs/source/_stylesheets/abjad.ily",
        f"{pathlib.Path(__file__).parent}/../../build/segment_stylesheet.ily",
    ],
    segment_name="16",
    current_directory=pathlib.Path(__file__).resolve().parent,
    cutaway=False,
    beam_pattern="meter",
    beam_rests=False,
    barline="||",
    rehearsal_mark="",
    fermata="scripts.ufermata",
    with_layout=True,
    extra_rewrite=False,
    # mm_rests=False,
)

maker.build_segment()
